### ISSUE TITLE
Ubuntu Trusty error

### ISSUE THREAD

**Issue by eluizbr** [pritunl/pritunl-client-electron#4]
We have de following error:

root@ubuntu:~# pritunl-client import https://SERVER:9700/k/1WCBj
Traceback (most recent call last):
  File "/usr/bin/pritunl-client", line 9, in <module>
    load_entry_point('pritunl-client==1.0.705.52', 'console_scripts', 'pritunl-client')()
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/__main__.py", line 220, in client_shell
    cli()
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 663, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 643, in main
    rv = self.invoke(ctx)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 990, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 836, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 463, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/__main__.py", line 96, in import_cmd
    data=json.dumps(data),
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

Any tip?

Thanks

**Comment by zachhuff386** [comment]
The link above is the view link, the uri link needs ot be used for import.

**Comment by eluizbr** [comment]
Same error:

root@ubuntu:~# pritunl-client import pritunl://SERVER:9700/ku/u8Gec
Traceback (most recent call last):
  File "/usr/bin/pritunl-client", line 9, in <module>
    load_entry_point('pritunl-client==1.0.705.52', 'console_scripts', 'pritunl-client')()
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/__main__.py", line 220, in client_shell
    cli()
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 663, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 643, in main
    rv = self.invoke(ctx)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 990, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 836, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/click/core.py", line 463, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/pritunl_client/__main__.py", line 96, in import_cmd
    data=json.dumps(data),
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl-client/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
